### ISSUE TITLE
Feature Request: Change order of levels in Add Member page.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-add-member-admin#23]
A support user would like to reorder the levels on the Add Member admin page.

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/adjust-order-of-member-levels-that-appear-on-add-member-from-admin-page/?skipped

**Comment by dparker1005** [comment]
Looking at the user's support ticket, the issue looks like their levels were not being sorted by their level IDs, which would be the expected behavior. I have not been able to replicate this behavior on a staging site with the information provided. If this is still an issue that anyone is still experiencing, please <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a> or leave a comment on this GitHub Issue so that we can look further into this.
