### ISSUE TITLE
Bug: +order creates new membership entry

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-add-member-admin#36]
As currently written, using the `+order` button for a user from the members list will cancel the user's old membership and give them a new one during the order creation process. This is because that page is a streamlined version of the entire "Add Member" page, which correctly has that membership change functionality built-in. The issue with the `+order` button creating new membership entries is that it can make it looks like users have signed up/cancelled in the PMPro reports when they really just had an order added.

Two feasible options are to remove the `+order` button altogether or to make that button go to the default "create order" page with as much info filled out on that page as possible. Completely removing that feature would mean that we would also need to build a workaround for people who were actively using that feature, so redirecting to the default "create order" page instead seems like the best solution.

**Comment by tictag** [comment]
For MODS only:
Further information contained here: https://www.paidmembershipspro.com/forums/topic/bug-add-member-from-admin-add-on-new-member-incremented-in-activity-email/

**Comment by tictag** [comment]
Whilst I appreciate that deprecating this feature, or rather, linking to the default 'Add New Order' feature is the likely candidate solution, I do believe that their are three solutions options:

– Remove the +Order feature (or at least link)
– Fix the +Order feature so that it doesn’t increment membership stats
– Fix the membership stats feature so that it doesn’t include those generated through the +Order feature
