### ISSUE TITLE
Plugin incompatible with wordpress 4.8.2 (multisite)

### ISSUE THREAD

**Issue by gdsbond** [strangerstudios/pmpro-add-member-admin#7]
Hi, I was working on a multisite on wordpress 4.8.2 and I was unable to access the membership levels. So upon deactivating this plugin and email template add on everything worked fine.

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported that should have fixed this bug. If this is still an issue that you are experiencing on your site, please <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a> or leave a comment on this GitHub Issue so that we can look further into this.
